### PR TITLE
build stable sort for graph iteration

### PR DESCRIPTION
**Pull request by sing1ee**
so we can get ***stable*** result!

### CODE REVIEW

**Comment by gumblex** [comment]
but you don't need to make everything a list...
I think only Line 26,27,29 is necessary. This branch has already been Python 2/3 compatible, so the xrange, itervalues are for the compatibility.

**Comment by sing1ee** [comment]
@gumblex thx

**Comment by wangbin** [comment]
for line 26, I suspect it might consume lots of memory if the dictionary is too large, also only keys are needed for sort, right? How about:

    giter = sorted(self.graph.keys())
    ...
    for n in giter:
        ws[n] = wsdef
        outSum[n] = sum((e[2] for e in self.graph[n]), 0.0)

**Comment by gumblex** [comment]
That's right

**Comment by sing1ee** [comment]
good points， thanks all！
I also have a question, what's the difference between "itervalues" and "dict.items"? what's the advantange and disadvantage? thx.

**Comment by gumblex** [comment]
`dict.items()` (Python 3) is `dict.iteritems()` (Python 2)
`list(dict.items())` (Python 3) is `dict.items()` (Python 2)

Here, the function `itervalues` in [_compat.py](https://github.com/fxsjy/jieba/blob/master/jieba/_compat.py#L14) is a made-up function for Py 2/3 compatibility, so as the xrange for Python 3.

**Pull request merged**
