### PR TITLE
sqlite support (better memory usage)

### PR DESCRIPTION
**Pull request by hinesmr**
This commit introduces jieba.initialize(sqlite = True|"/path/to/jieba.db")
    
Sqlite is implemented using SqlAlchemy to create two, indexed sqlite tables
in a single db file (default /tmp/jieba.db).
    
If the user does not choose sqlite, nothing will happen. Just default to
the in-memory version of Jieba.
    
Performance seems very good and Memory usage is *much* better.
   
I am using this in a mobile application. (The final DB file is about 24 MB,
which can be downloaded to the mobile application using after it is installed.)
    
Comments welcome!

### CODE REVIEW

**Comment by gumblex** [comment]
It will be good if the memory cost is reduced. But I can see some problems in the code.

* The SqlAlchemy breaks the zero dependency. You can try to use sqlite3 directly or at least wrap it in a try…except ImportError clause.
* It seems that a user dictionary can be mixed up with the default dictionary.
* The performance of the code is not well tested. Some of the function calls or if-clauses may reduce speed. This can be tested using various tools.
* There's a print in L118, you can't do this in a library.

The code should be reviewed to ensure there's no obvious compatibility or performance problems.

**Comment by hinesmr** [comment]
Great comments! Thank you. I will try to make a new patch soon =)

Regarding comment #3: The patch still has the default dictionary as the default - there is no change there. Sqlite is only used for the cache, not the dictionary itself. If the user does not configure sqlite, then the cache will still be the old cache.

**Comment by gumblex** [comment]
The point of # 2 (not 3) is that, if a user loads a user dictionary in app A, and he then loads the default one in app B, he will get the cache for the user dictionary instead of generate a new cache for the default dictionary. We currently use a MD5 hash for the file name of the cache for the user dictionary to prevent conflicts. (L103) You can follow this behavior.

**Comment by hinesmr** [comment]
Ah, yes. I see. Thanks.

**Pull request closed without merging**
